In [6]:
import pandas as pd

In [70]:
#불러올 때마다 주소를 바꿔주면 된다.
trans_json = pd.read_json('make_service_for_me/vq6_47FLOeI.json')
trans_json

,title,upload_date,transcript
0,편신~장호준쉐프의 크랩 와사비 포테이토야~...,2025-01-15,오늘 먹어볼 변신은 장호준 세프의
1,편신~장호준쉐프의 크랩 와사비 포테이토야~...,2025-01-15,크랩 와사비 포테이토 GS 25
2,편신~장호준쉐프의 크랩 와사비 포테이토야~...,2025-01-15,2500원 크랩이 살아 있군 맛은
3,편신~장호준쉐프의 크랩 와사비 포테이토야~...,2025-01-15,신선한 크레 맛에 부드러운 감자
4,편신~장호준쉐프의 크랩 와사비 포테이토야~...,2025-01-15,샐러드에 약한 와사비 소스가 약간
5,편신~장호준쉐프의 크랩 와사비 포테이토야~...,2025-01-15,달달하니 완전 맛있어 존도 다섯 개
6,편신~장호준쉐프의 크랩 와사비 포테이토야~...,2025-01-15,중 몇 개야 맛 다섯 개야

In [71]:
trans_json['transcript']

0     오늘 먹어볼 변신은 장호준 세프의
1      크랩 와사비 포테이토 GS 25
2     2500원 크랩이 살아 있군 맛은
3      신선한 크레 맛에 부드러운 감자
4     샐러드에 약한 와사비 소스가 약간
5    달달하니 완전 맛있어 존도 다섯 개
6         중 몇 개야 맛 다섯 개야
Name: transcript, dtype: object

In [72]:
# 자막 스크립트 결합

combined_text = trans_json['transcript'].str.cat(sep=' ')

# 새로운 DataFrame 생성 (기존의 열들과 합쳐서 생성)
new_df = pd.DataFrame([combined_text], columns=['Combined_Transcript'])
new_df = pd.concat([trans_json[['title', 'upload_date']], new_df], axis=1)

# 0번 인덱스만 출력
final_df = new_df.iloc[:1].reset_index(drop=True)

In [73]:
final_df

,title,upload_date,Combined_Transcript
0,편신~장호준쉐프의 크랩 와사비 포테이토야~...,2025-01-15,오늘 먹어볼 변신은 장호준 세프의 크랩 와사비 포테이토 GS 25 2500원 크랩이...